apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pii-service
  labels:
    cloud.googleapis.com/location: us-east5
spec:
  template:
    spec:
      containerConcurrency: 50
      timeoutSeconds: 300
      serviceAccountName: ash-data-reader@ashley-services-development.iam.gserviceaccount.com
      containers:
      - name: service
        image: us-east1-docker.pkg.dev/ashley-repositories/ashley-repos-docker/pii-service:latest
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: development
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai_api_key
              key: latest
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 1
          tcpSocket:
            port: 8000
